task1:
	g++ -o task1 Task1.cpp
	echo "task1 has been compiled successfully!"
	./task1


task2:
	g++ -o task2 Task2.cpp
	echo "task2 has been compiled successfully!"
	./task2

clean:
	rm -f task1 task2